/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: shiro_hime (https://sketchfab.com/shiro_hime)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xyz-school-course-work-cozy-cyberpunk-cafe-62574405638d4f608d834aadb1d52044
Title: [XYZ School] - Course Work - Cozy Cyberpunk Cafe
*/

import React, { useRef } from 'react'
import { a } from '@react-spring/three'
import { useGLTF } from '@react-three/drei'
import model from '../assets/xyz_school_-_course_work_-_cozy_cyberpunk_cafe.glb'
import { useFrame, useThree } from '@react-three/fiber'
import {useEffect} from 'react'
const Model = ({isRotating,setIsRotating, ...props}) =>{
  const modelRef = useRef()
  const { nodes, materials } = useGLTF(model)
  const {gl, viewport} = useThree();

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches 
    ? e.touches[0].clientX 
    : e.clientX;

    lastX.current = clientX;
  }
   
  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);

  }
  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if(isRotating){
      
    const clientX = e.touches 
    ? e.touches[0].clientX 
    : e.clientX;

    const delta = (clientX - lastX.current) / viewport.width;
    modelRef.current.rotation.y += delta * Math.PI * 0.01;

    lastX.current = clientX;
    rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  }

  useEffect(() => {
    const canvas = gl.domElement
    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointermove', handlePointerMove);
    canvas.addEventListener('pointerup', handlePointerUp);
    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown);
      canvas.removeEventListener('pointermove', handlePointerMove);
      canvas.removeEventListener('pointerup', handlePointerUp);
    }
  },[gl,handlePointerDown,handlePointerMove,handlePointerUp]);


  useFrame(() => {
    if(!isRotating){
      rotationSpeed.current *= dampingFactor;
      if(Math.abs(rotationSpeed.current) < 0.001){
        rotationSpeed.current = 0;
      }
      modelRef.current.rotation.y += rotationSpeed.current;
    }else{
      const rotation = modelRef.current.rotation.y;
      const normalizedRotation = ((rotation % (2*Math.PI)) + 2*Math.PI) % (2*Math.PI);
      switch(true){
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
        setCurrentStage(4);
        break
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3: 
        setCurrentStage(3);
        break
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
        setCurrentStage(2);
        break
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
        setCurrentStage(1);
        break
        default:
          setCurrentStage(null);  
      }
    }
  });
  return (
    <a.group ref={modelRef} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn12_0'].geometry}
          material={materials.ourse_blinn12}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn9_0'].geometry}
          material={materials.ourse_blinn9}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong12_0'].geometry}
          material={materials.ourse_phong12}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_phong13_0.geometry}
          material={materials.phong13}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert16_0'].geometry}
          material={materials.ourse_lambert16}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn13_0'].geometry}
          material={materials.ourse_blinn13}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn1_0'].geometry}
          material={materials.ourse_blinn1}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn4_0'].geometry}
          material={materials.ourse_blinn4}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn14_0'].geometry}
          material={materials.ourse_blinn14}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong13_0'].geometry}
          material={materials.ourse_phong13}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_lambert20_0.geometry}
          material={materials.lambert20}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong16_0'].geometry}
          material={materials.ourse_phong16}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert4_0'].geometry}
          material={materials.ourse_lambert4}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert10_0'].geometry}
          material={materials.ourse_lambert10}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn5_0'].geometry}
          material={materials.ourse_blinn5}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn2_0'].geometry}
          material={materials.ourse_blinn2}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong11_0'].geometry}
          material={materials.ourse_phong11}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn6_0'].geometry}
          material={materials.ourse_blinn6}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert9_0'].geometry}
          material={materials.ourse_lambert9}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong1_0'].geometry}
          material={materials.ourse_phong1}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong15_0'].geometry}
          material={materials.ourse_phong15}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn3_0'].geometry}
          material={materials.ourse_blinn3}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_blinn24_0.geometry}
          material={materials.blinn24}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong14_0'].geometry}
          material={materials.ourse_phong14}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert13_0'].geometry}
          material={materials.ourse_lambert13}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_blinn6_0.geometry}
          material={materials.blinn6}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_blinn25_0.geometry}
          material={materials.blinn25}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong8_0'].geometry}
          material={materials.ourse_phong8}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert3_0'].geometry}
          material={materials.ourse_lambert3}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong6_0'].geometry}
          material={materials.ourse_phong6}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn17_0'].geometry}
          material={materials.ourse_blinn17}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert8_0'].geometry}
          material={materials.ourse_lambert8}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_phong7_0.geometry}
          material={materials.phong7}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_phong3_0.geometry}
          material={materials.phong3}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn15_0'].geometry}
          material={materials.ourse_blinn15}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn8_0'].geometry}
          material={materials.ourse_blinn8}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong17_0'].geometry}
          material={materials.ourse_phong17}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong5_0'].geometry}
          material={materials.ourse_phong5}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_phong18_0.geometry}
          material={materials.phong18}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong19_0'].geometry}
          material={materials.ourse_phong19}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong4_0'].geometry}
          material={materials.ourse_phong4}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn11_0'].geometry}
          material={materials.ourse_blinn11}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn10_0'].geometry}
          material={materials.ourse_blinn10}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn7_0'].geometry}
          material={materials.ourse_blinn7}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_lambert15_0.geometry}
          material={materials.lambert15}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn19_0'].geometry}
          material={materials.ourse_blinn19}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong18_0'].geometry}
          material={materials.ourse_phong18}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn21_0'].geometry}
          material={materials.ourse_blinn21}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn22_0'].geometry}
          material={materials.ourse_blinn22}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_phong15_0.geometry}
          material={materials.phong15}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert14_0'].geometry}
          material={materials.ourse_lambert14}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert5_0'].geometry}
          material={materials.ourse_lambert5}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn23_0'].geometry}
          material={materials.ourse_blinn23}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert15_0'].geometry}
          material={materials.ourse_lambert15}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert18_0'].geometry}
          material={materials.ourse_lambert18}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_blinn17_0.geometry}
          material={materials.blinn17}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn16_0'].geometry}
          material={materials.ourse_blinn16}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert2_0'].geometry}
          material={materials.ourse_lambert2}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert12_0'].geometry}
          material={materials.ourse_lambert12}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_phong16_0.geometry}
          material={materials.phong16}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_phong12_0.geometry}
          material={materials.phong12}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_phong1_0.geometry}
          material={materials.phong1}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_blinn8_0.geometry}
          material={materials.blinn8}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong24_0'].geometry}
          material={materials.ourse_phong24}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert7_0'].geometry}
          material={materials.ourse_lambert7}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert6_0'].geometry}
          material={materials.ourse_lambert6}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong10_0'].geometry}
          material={materials.ourse_phong10}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong7_0'].geometry}
          material={materials.ourse_phong7}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn20_0'].geometry}
          material={materials.ourse_blinn20}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong9_0'].geometry}
          material={materials.ourse_phong9}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong2_0'].geometry}
          material={materials.ourse_phong2}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_blinn18_0'].geometry}
          material={materials.ourse_blinn18}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_blinn22_0.geometry}
          material={materials.blinn22}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_phong25_0'].geometry}
          material={materials.ourse_phong25}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert17_0'].geometry}
          material={materials.ourse_lambert17}
        />
        <mesh
          
          Shadow
          geometry={nodes.polySurface2027_lambert11_0.geometry}
          material={materials.lambert11}
        />
        <mesh
          
          Shadow
          geometry={nodes['polySurface2027_��ourse_lambert11_0'].geometry}
          material={materials.ourse_lambert11}
        />
      </group>
    </a.group>
  )
}

export default Model;